### ISSUE TITLE
Reason for embedding source on Windows?

### ISSUE THREAD

**Issue by jyapayne** [Araq/libffi#5]
I've recently been able to build both 32 bit and 64 bit DLLs for windows for libffi, which I could file a PR for and include them in this repo depending on if it's a good solution.

@Araq Is there a reason why the sources were embedded vs linking to the dlls?

**Comment by Araq** [comment]
Fools telling me about how binaries in a git repo are so much worse than caring about your users.

**Comment by jyapayne** [comment]
Alright. I'll make the PR and see what you make of it then :)
